language: python
python:
    - "3.8.3"

before_install:
  - sudo apt-get -y install libbz2-dev

install:
    - pip install -r requirements.txt
    - python setup.py install

script:
    - pytest py/picca/test/test_cor.py -s
